language: php
php:
- 5.5
env:
- TRAVIS_NODE_VERSION="6"
before_install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install $TRAVIS_NODE_VERSION
install:
- npm install
- npm run setup
before_script:
- php --version
- node --version
- npm --version
script:
- npm run compile
- npm test
before_deploy:
- rm -rf node_modules pattern-lab/{core,config,vendor}
deploy:
- provider: s3
  access_key_id: AKIAJOBGJEAJOHTWTKBQ
  secret_access_key:
    secure: WCcg4hydNf3gaT2Su4k3wkahbgMmEjFAqeQHQgKy490+2QVzNioftIAKzh2vwkUM1ig17RaV2zm6REUREHI6aLyIuQgwXvPp0S8tHzWrXeWvshcph+hTkG56dy6e2M8gpKF0EP6UPyfzrE/g19aFW5r5KK0t3vn/EyPH1uEKbyK8/tFvWXRgRyMQxzj/yZxhmcn/EuRplcJ0Y/iAvl7xz9KOHOlTH19mH7w4i4PqGWG+vSHDzB4KG9GYUS8ud4JPNYeMtcmrau33fFNkZTyrpR5cSW4hBak6qgNtOju/xiknqe7880XqIGlWr4j5x8/H5VxYZog17zOS7jB8FjyCacLKDPYs+PknDQy4Nm+JNqSFRnY5enLtiXDSpL6m1vJ3pFS9LK2YsISy6heYU5YsVXvXTXbLKsy2j20Jl5fl0AXnAGZeQvdVl1qmuZYBLcfxBsKafCxUTp6dNCRyw7ehSsSuGjkZeX8kuzHqVe3uumfLMxqMMFp43cjwojUsjv1ddprmkXOr5EV9Ci0WtTv9DEGdkQvTbVHH64bm+/i6GdwO9A/Ue1pnioqVW+bfMbf6Qez6NOb02DLHAvXiJjDGrTINd3Z2X+bTwPEmY4jXr7J1Kqt2w09nB9RUDZ+Ol5ItcWyGNJ43/5+kPpP9WS+Xsjn96LjklHVUrwqzUgJrgY8=
  bucket: fable-phase2-brand
  upload-dir: patternlab
  acl: public_read
  skip_cleanup: true
  on:
    branch: master
- provider: npm
  email: evanlovely@gmail.com
  on:
    tags: true
  api_key:
    secure: JbUQJP2vR3sBDLCtsHyEJsc9yRLPWCP6BeBaSPTbrNB7NOedGH9gbtRMxCEHytVQTqdaux7l1T+y+vo/mmMjXHq3T6S4tTbuNZC8xe0m1gt+jo7FGAUEynz5SQOu2Fnx1s5YPf+0VQIXaDhE3TsF8Rm8zoTyvziv7uFUIsrIpnlWyoJHW42wpgnHjDQS3geVnKMIcSCg2qn8U/qmusT0SGwVC0BxL3vTfP8WiYl338zURyU4I590Wl8Tg6uci8q0G9Wb7NcXnH+/SmeZWsZdjtD+lgeRnBFzOBuWPIdDrV23Lm2TRAetpvwgFjugbOYhiiY1J/7jIyobJIg+LRuBBXGnKAeOLw1atIWI4fI+ZiBkf3cnOkECxQYwyPtFaqN2NTiPFhX/BYtyS9kHODKpDhk6YkgqFYRyNdz/nOHbH6BPeUApW1Jxxs41AHqtU0xqpw6tRnuBXJ2rBlwEK+mECjtwidUWsTI0skEQXb1p9iNxFo4b5W5mu4ylijAwnY96T2BNMeR9R0BSD7gkOnhgFDiVmzk0yB28Nvb2qSA8gf2i53ZtKjrlTnYGwO/Y6OpTJaRPl2OBLKITi8smOWnJnDj1V7VSlMmfTjoX4MQAX2T2gBNWsNwmIiRZ8SAhwA/nWbBT6hXlKwggHQ2qhlG9IxYNMDHoJ3CiQXyJdFs/rMY=
notifications:
  slack:
    secure: OYvP7hDyn5zafMsazU07AuLcTq2Wd48aJi86Im3U+h/VlK6JGN8IbyZnTL0D3e7P0etA6Dyrp2cntuxSC/a1Xbxq72dTm4SRRx1NOcf1EcxAUDlK6EehmpweX1gPC3hBjCgsodCr3ZAsEs0b8M3FNddoRpCa+D7xlHg2hREkImw0+7IHa0HidTj6/2Pw5eEYtKIfPqGrEjiY301DcQQHQqTsXlzj3U7w+ZvpSD7H4F7Kzmjz5jf34J2nxw3zdLZmfOo3RRcT/6LrLirYNjcmGROVWgDNnfL5AsPJJnRsoNJit2j/7E1dAh4fkTzLKJbEchyM35PM9We8pmnyVxnBvch/gKQQVjspERo5vjtMO8IOCIqQcHpPgNZ46TdU2wbhmF2JTw8oSYoBbSDWMBFIKzwT7MpDIb8/872ksVKsh5l7UpwhB45jH8oIrC2/9HOmbjoGT3m2MJ2rYbGAQVmEd1HpHHQPEA8r0RQpjz4g8nrsd0x/cI2Sc/DqKwK61H7fvJ5oBIhwMseaX2Nznge0Bzw+WkxnU80jVGyao/7aA1wuZuekupukeY2yxuONyfwafGD2f4MmoLc//UJ6zdn0ZuC22ntORJnZVnW9V8VZf01vVEoiM/K6uRhFAA48jKArggq9Wgfp/l8mBs7BWL51QAbs8eBCUz/HjkpyAIEQrX8=
