language: php
# Tests will be for each version in `php` combined with each node version in `env`
php:
  - 5.5
env:
  - TRAVIS_NODE_VERSION="6"
before_install:
#  - composer clear-cache
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
install:
  - npm install
  - npm run setup
before_script:
  - php --version
  - node --version
  - npm --version
script: 'npm run compile'
